server:
  port: 8080

spring:
  application:
    name: graalvm-service
  datasource:
    url: jdbc:postgresql://localhost:5432/graalvm?useSSL=false
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/master-changelog.xml