version: '3.7'

services:
  graalvm-database:
    image: postgres:15-alpine
    container_name: graalvm_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=graalvm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data
#      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"

  graalvm-service:
    image: graalvm-service:latest
    container_name: graalvm_service
    restart: unless-stopped
    build:
      context: ../
      #     dockerfile: Dockerfile - так делали всегда
      dockerfile: ./docker/Dockerfile.native # так собираем нативный образ
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - graalvm-database

volumes:
  db: { }
